theme: jekyll-theme-cayman
title: Smart SVG Viewer
description: SVG image viewer with Thumbnail Gallery for UI/UX Designers, Web Developers, Graphics Designers
show_project_link: false
show_downloads: false

installer_version: 0.5.0 alpha (build 1042)
installer_filesize_kb: 440
executable_filesize_kb: 80
installer_filename: SmartSvgViewerSetup.msi
installer_url: https://github.com/sla80/SmartSvgViewer/raw/master/SmartSvgViewerSetup.msi
