theme: jekyll-theme-cayman
title: Smart SVG Viewer
description: Free SVG image viewer for Windows, with Thumbnail Gallery and Alpha channel support
lang: en_US
logo: https://sla80.github.io/SmartSvgViewer/images/logo.svg
summary_image:
  path: https://sla80.github.io/SmartSvgViewer/images/site-summary.png
  width: 1280
  height: 640

baseurl: /SmartSvgViewer
html_lang: en
yandex_metrika: 67783888
google_analytics: UA-179561008-1

include:
  - sitemap.xml
  - robots.txt
  - site.webmanifest

installer_version: 0.5.0 alpha (build 1302)
installer_filesize_kb: 444
executable_filesize_kb: 90
installer_filename: SmartSvgViewerSetup.msi
installer_url: https://github.com/sla80/SmartSvgViewer/raw/master/SmartSvgViewerSetup.msi
