theme: jekyll-theme-cayman
title: Smart SVG Viewer
description: Free SVG image viewer for Windows, with Thumbnail Gallery and Transparency Grid
lang: en_US
logo: https://sla80.github.io/SmartSvgViewer/images/logo.svg
summary_image:
  path: https://sla80.github.io/SmartSvgViewer/images/site-summary.png
  width: 1280
  height: 640

baseurl: /SmartSvgViewer
html_lang: en
yandex_metrika: 67783888
google_analytics: G-KPN9LS8Y8V

include:
  - sitemap.xml
  - robots.txt
  - site.webmanifest

installer_version: 0.5.0.1645
installer_version_visual: 0.5.0 alpha (build 1645)
executable_filesize_kb: 135
installer_filesize_kb_x64: 724
installer_filesize_kb_arm64: 724

installer_filename_x64: SmartSvgViewerSetup_x64.msi
installer_filename_arm64: SmartSvgViewerSetup_ARM64.msi
