theme: jekyll-theme-cayman
title: Smart SVG Viewer
description: Free SVG image viewer for Windows, with Thumbnail Gallery and Alpha channel support
baseurl: /SmartSvgViewer
lang: en
yandex_metrika: 67783888
google_analytics: UA-179561008-1

include:
 - sitemap.xml
 - robots.txt

installer_version: 0.5.0 alpha (build 1225)
installer_filesize_kb: 452
executable_filesize_kb: 87
installer_filename: SmartSvgViewerSetup.msi
installer_url: https://github.com/sla80/SmartSvgViewer/raw/master/SmartSvgViewerSetup.msi
